### ISSUE TITLE
Error in Refprop interface

### ISSUE THREAD

**Issue by MiaRun** [CoolProp/CoolProp#1624] opened 2017-12-21 03:51 UTC
Hi:
    I can't use CoolProp Refprop interface successfully. 

   * windows 7
   * Refprop (DDL  version 9.1)  
         echo %RPPRFIX%
         C:\Program Files (x86)\REFPROP\
   * CoolProp 6.1.0
 
Here are the problems I met:
1 code :
```
import CoolProp.CoolProp as CP
CP.set_config_string(CP.ALTERNATIVE_REFPROP_PATH,'c:\\Program Files (x86)\\REFPROP\\')
CP.get_global_param_string("REFPROP_version")
```
result:
```
         1 import CoolProp.CoolProp as CP
         2 CP.set_config_string(CP.ALTERNATIVE_REFPROP_PATH,'c:\\Program Files (x86)\\REFPROP\\')
----> 3 CP.get_global_param_string("REFPROP_version")

CoolProp\CoolProp.pyx in CoolProp.CoolProp.get_global_param_string (CoolProp\CoolProp.cpp:38800)()

CoolProp\CoolProp.pyx in CoolProp.CoolProp.get_global_param_string (CoolProp\CoolProp.cpp:38740)()

RuntimeError: Unknown exception
```

2 code:
```
CP.PropsSI('D','P',101325,'T',300,'REFPROP::Water')
```
result:
```
CoolProp\CoolProp.pyx in CoolProp.CoolProp.PropsSI (CoolProp\CoolProp.cpp:41707)()

CoolProp\CoolProp.pyx in CoolProp.CoolProp.PropsSI (CoolProp\CoolProp.cpp:41495)()

CoolProp\CoolProp.pyx in CoolProp.CoolProp.__Props_err2 (CoolProp\CoolProp.cpp:39709)()

ValueError: Initialize failed for backend: "REFPROP", fluid: "Water" fractions "[ 1.0000000000 ]"; error: You cannot use the REFPROPMixtureBackend. : PropsSI("D","P",101325,"T",300,"REFPROP::Water")
```

I have added the Refprop in the path environment, but still can't use the Refprop.

thanks~

**Comment by ibell** [comment] 2017-12-21 04:14
I have edited your issue to fix the formatting in markdown.

**Comment by ibell** [comment] 2017-12-21 04:18
If you have installed REFPROP correctly, there should be no need to adjust the REFPROP path.

1. First try to update REFPROP and CoolProp.  You can pip install the dev version of CoolProp : http://www.coolprop.org/coolprop/wrappers/Python/index.html#automatic-installation .  For REFPROP email me: ian.bell@nist.gov
2. Make sure the REFPROP GUI is working properly.
3.  When in doubt, reinstall REFPROP

**Comment by MiaRun** [comment] 2017-12-21 07:29
I have tried these methods, however the error remains.

**Comment by ibell** [comment] 2018-01-05 04:30
Ah I think the issue is with your version of 9.1 - some of them had messed up intel runtime libraries.  Please email my address above and I will send you the patch for 9.1.1 which statically links them and fixes some issues.

**Comment by ibell** [comment] 2018-01-18 04:59
Bump.

**Comment by MiaRun** [comment] 2018-01-22 12:03
I tried adding the file "REFPRP64.DLL" into the folder where I wrote the python code. It worked.
But I don't know why.

**Comment by jowr** [comment] 2018-01-22 18:25
On Windows, the current directory is automatically added to the path. Maybe you have some problems with your PATH? Maybe there is a typo in your settings...

**Comment by ibell** [comment] 2018-01-22 22:55
Yes, or, the more likely option is that the intel runtimes that were needed
for REFPROP 9.1 are not in the path.  This was always very difficult to
debug, which is why they are now statically compiled into REFPROP.  This is
why I recommended you email me for the patch to 9.1.1.  We have plenty of
users of REFPROP 9.1.1 who call it from CoolProp without problem.

**Comment by ibell** [comment] 2019-01-13 00:16
Closing due to lack of input

**Closed** 2019-01-13 03:47 UTC
Labels: REFPROP

**Comment by shanknatesh** [comment] 2019-06-18 18:13
Having the same issue on v.10. Unable to load refrigerant mixture. This is the only version I have installed on my machine.

`ValueError: Initialize failed for backend: "REFPROP", fluid: "R404.MIX" fractions "[ 1.0000000000 ]"; error: Unable to load mixture: R404.MIX : PropsSI("T","P",1597271.854,"Q",0,"REFPROP::R404.MIX")`

**Comment by ianhbell** [comment] 2019-06-18 18:18
@shanknatesh Please open a new issue.  Especially interesting is what operating system you use, I suspect something like linux or OSX, given that we have this open issue: https://github.com/usnistgov/REFPROP-issues/issues/168

**Comment by shanknatesh** [comment] 2019-06-18 18:36
> @shanknatesh Please open a new issue. Especially interesting is what operating system you use, I suspect something like linux or OSX, given that we have this open issue: [usnistgov/REFPROP-issues#168](https://github.com/usnistgov/REFPROP-issues/issues/168)

I am using windows 10. Didn't see any solutions to this issue on the forum for windows OS.
