### ISSUE TITLE
Error with Cycle Calculation

### ISSUE THREAD

**Issue by TianbiaoHe** [CoolProp/CoolProp#1461] opened 2017-03-22 12:48 UTC
Hi,
I am using the source code from http://coolprop.sourceforge.net/coolprop/python-cycles.html 

```python
_import CoolProp
from CoolProp.Plots import PropertyPlot
from CoolProp.Plots import SimpleCompressionCycle
pp = PropertyPlot('HEOS::R134a', 'PH', unit_system='EUR')
pp.calc_isolines(CoolProp.iQ, num=11)
cycle = SimpleCompressionCycle('HEOS::R134a', 'PH', unit_system='EUR')
T0 = 280
pp.state.update(CoolProp.QT_INPUTS,0.0,T0-10)
p0 = pp.state.keyed_output(CoolProp.iP)
T2 = 310
pp.state.update(CoolProp.QT_INPUTS,1.0,T2+15)
p2 = pp.state.keyed_output(CoolProp.iP)
pp.calc_isolines(CoolProp.iT, [T0-273.15,T2-273.15], num=2)
cycle.simple_solve(T0, p0, T2, p2, 0.7, SI=True)
cycle.steps = 50
sc = cycle.get_state_changes()
pp.draw_process(sc)
import matplotlib.pyplot as plt
plt.close(cycle.figure)
pp.show()_
```

Error Occurs.
```
ValueError                                Traceback (most recent call last)
<ipython-input-32-f3f6371f62b0> in <module>()
      2 from CoolProp.Plots import PropertyPlot
      3 from CoolProp.Plots import SimpleCompressionCycle
----> 4 pp = PropertyPlot('HEOS::R134a', 'PH', unit_system='EUR')
      5 pp.calc_isolines(CoolProp.iQ, num=11)
      6 cycle = SimpleCompressionCycle('HEOS::R134a', 'PH', unit_system='EUR')

C:\Users\thinkpad\Anaconda3\lib\site-packages\CoolProp\Plots\Plots.py in __init__(self, fluid_name, graph_type, **kwargs)
     66             graph types
     67         """
---> 68         super(PropertyPlot, self).__init__(fluid_name, graph_type, **kwargs)
     69         self._isolines = {}
     70         #self._plines = {}

C:\Users\thinkpad\Anaconda3\lib\site-packages\CoolProp\Plots\Common.py in __init__(self, fluid_ref, graph_type, unit_system, tp_limits, **kwargs)
    673         # call the base class
    674         state = process_fluid_state(fluid_ref)
--> 675         Base2DObject.__init__(self, graph_type[1], graph_type[0], state, **kwargs)
    676 
    677     @property

C:\Users\thinkpad\Anaconda3\lib\site-packages\CoolProp\Plots\Common.py in __init__(self, x_type, y_type, state, small)
    328         if small is not None: self._small = small
    329         else: self._small = 1e-7
--> 330         if state is not None: self.state = state
    331         else: self._state = None
    332 

C:\Users\thinkpad\Anaconda3\lib\site-packages\CoolProp\Plots\Common.py in state(self, value)
    351         #self._T_small = self._state.trivial_keyed_output(CoolProp.iT_critical)*self._small
    352         #self._P_small = self._state.trivial_keyed_output(CoolProp.iP_critical)*self._small
--> 353         self._T_small = self.critical_state.keyed_output(CoolProp.iT)*self._small
    354         self._P_small = self.critical_state.keyed_output(CoolProp.iP)*self._small
    355 

C:\Users\thinkpad\Anaconda3\lib\site-packages\CoolProp\Plots\Common.py in critical_state(self)
    339     def critical_state(self):
    340         if self._critical_state is None and self._state is not None:
--> 341             self._critical_state = get_critical_point(self._state)
    342         return self._critical_state
    343     @property

C:\Users\thinkpad\Anaconda3\lib\site-packages\CoolProp\Plots\Common.py in get_critical_point(state)
     43         try: new_state.specify_phase(CoolProp.iphase_critical_point)
     44         except: pass
---> 45         new_state.update(CoolProp.PT_INPUTS, crit_state.p, crit_state.T)
     46         #new_state.update(CoolProp.DmolarT_INPUTS, crit_state.rhomolar, crit_state.T)
     47         return new_state

CoolProp\AbstractState.pyx in CoolProp.CoolProp.AbstractState.update (CoolProp\CoolProp.cpp:17915)()

CoolProp\AbstractState.pyx in CoolProp.CoolProp.AbstractState.update (CoolProp\CoolProp.cpp:17807)()

ValueError: solver_rho_Tp was unable to find a solution for T=    374.21, p=4.05928e+06, with guess value     3599.4
```

**Comment by spinnau** [comment] 2017-04-19 14:20
This issue is a duplicate of #1375.

The error is not directly related to the cycle calculation and is raised by a call of the `AbstractState::update()` method with `T_crit` and `p_crit` as input pairs and phase specified as `iphase_critical_point`.

**Comment by thorade** [comment] 2017-07-14 08:11
Closing as it seems to be a duplicate.
Please reopen if it is a different issue.

**Closed by thorade** 2017-07-14 08:11 UTC
