### ISSUE TITLE
Isopentane Dynamic Viscosity and Thermal Conductivity

### ISSUE THREAD

**Issue by MarioKrstovic** [CoolProp/CoolProp#1579] opened 2017-10-27 00:45 UTC
Hi, 

Cool Prop  does not want to solve me the Dynamic Viscosity and Thermal Conductivity for Isopentane. 

Does CoolProp have that options for Isopentane or I am doing something wrong.  I tried with multiple pressures and temperatures and it did not wanted to work. 

Thank you for your answer.

Kind regards,

Mario Krstovic

**Comment by ibell** [comment] 2017-10-27 00:46
What error do you get?

**Comment by MarioKrstovic** [comment] 2017-10-27 00:50
I get this error:

Warning: Thermal conductivity model is not available for this fluid 
Error using CoolPropMATLAB_wrap
Failure in function PropsSI.

Error in CoolProp.PropsSI (line 2)
  [varargout{1:max(1,nargout)}] =
  CoolPropMATLAB_wrap(202,'_wrap_PropsSI',varargin{:});

**Comment by MarioKrstovic** [comment] 2017-10-27 02:55
Also, I have seen that it is making the same problem with Isohextane

**Comment by jowr** [comment] 2017-10-29 18:13
I am afraid the error message is correct. There is no model in the CoolProp database - if you know of a high quality correlation and can provide a link to a publication with equations, someone could implement it. You are always welcome to contribute code as well.

**Comment by thorade** [comment] 2017-11-01 15:44
https://github.com/CoolProp/CoolProp/blob/master/FAQ.md
http://www.coolprop.org/fluid_properties/fluids/Isopentane.html#fluid-isopentane
http://www.coolprop.org/fluid_properties/fluids/Isohexane.html#fluid-isohexane

For Isopentane, references for viscosity and thermal conductivity are listed.

**Comment by henningjp** [comment] 2017-11-02 01:19
While the references are listed, the json file under CoolProp/dev/fluids looks to have some correlation data in it for conductivity, but not for viscosity.  Perhaps someone meant to implement it, but didn't finish?

**Comment by MarioKrstovic** [comment] 2017-11-02 12:49
[isopentane_funa.txt](https://github.com/CoolProp/CoolProp/files/1437727/isopentane_funa.txt)
[Isopentane1.txt](https://github.com/CoolProp/CoolProp/files/1437728/Isopentane1.txt)

Hi, I programmed those two parameters in Matlab this weekend. I took the points from https://www.google.co.uk/search?q=NIST+Chemistry+Webbook&oq=NIST+Chemistry+Webbook&aqs=chrome..69i57j69i60l2j0l3.68j0j8&sourceid=chrome&ie=UTF-8
and created the polynomials. 

I have not still made it re-presentable. I will send you what I have until now, this is for me now doing job but maybe is not good enough
[isopentane.xlsx](https://github.com/CoolProp/CoolProp/files/1437707/isopentane.xlsx)

I putted my function into the notepad since it was not able to send it a m files. I can write explanations this weekend what means what.

**Comment by MarioKrstovic** [comment] 2017-11-02 12:49
[isopentane_funa.txt](https://github.com/CoolProp/CoolProp/files/1437750/isopentane_funa.txt)

**Comment by henningjp** [comment] 2017-11-02 19:59
@MarioKrstovic , My mistake.  Isopentane uses the Chung model for viscosity which requires very few parameters.  These transport properties were implemented back in 2015, and should be available since v5.1.2 and is certainly available in v6.0.0 and v6.1.0.

```python
import CoolProp.CoolProp as CP
# print out CoolProp Version
print ('CoolProp version: {0}'.format(CP.get_global_param_string("version")))
# Set Standard Temperature [K] and Pressure [Pa]
T = 395.16
print ('Temperature = {0} K'.format(T))
P = 101325
print ('Pressure = {0} Pa'.format(P))
# Get Viscosity, V, in [Pa-s]
print ('Viscosity = {0} Pa-s'.format(CP.PropsSI('V','T',T,'P',P,'Isopentane')))
# Get Thermal Conductivity, L, in [W/m-K]
print ('Thermal Conductivity = {0} W/m-K'.format(CP.PropsSI('L','T',T,'P',P,'Isopentane')))
```
Output from my installation is as follows:
```
CoolProp version: 6.1.1dev
Temperature = 395.16 K
Pressure = 101325 Pa
Viscosity = 9.30871328972e-06 Pa-s
Thermal Conductivity = 0.0262008252014 W/m-K
```
Looks like maybe you are using an old version of CoolProp.  Please update to 6.1.0 and try again.

**Comment by henningjp** [comment] 2017-11-09 01:58
@MarioKrstovic  Is this resolved?  If so, please close.

**Comment by thorade** [comment] 2017-11-16 09:21
I can confirm that viscosity and conductivity are available for isopentane, using this python snippet:
```python
import CoolProp as CP
from CoolProp.CoolProp import PropsSI
print(CP.__version__)
print(CP.__gitrevision__)

FluidName = 'Isopentane'
T =300
P=101325

# Get Viscosity, V, in [Pa-s]
print (PropsSI('viscosity','T',T,'P',P,FluidName))
# Get Thermal Conductivity, L, in [W/m-K]
print (PropsSI('conductivity','T',T,'P',P,FluidName))
```

For Isohexane, open literature would be needed, but does not exist, or is not known.
Closing for now, you can still comment or reopen.

**Closed by thorade** 2017-11-16 09:21 UTC
