### ISSUE TITLE
Problems running the VB.NET and C# wrappers

### ISSUE THREAD

**Issue by mattcasto** [CoolProp/CoolProp#1190] opened 2016-08-17 19:07 UTC
I have spent some time trying to run the latest VB.NET and C# wrapper projects, and I can't get anything to run. If I clone this github repo, copy the  open the wrappers\VB.NET\WpfApplication1.sln and run I get the following exception.

> Unable to find an entry point named '_get_errstring_copy@4' in DLL 'C:\CoolProp\CoolProp.dll'.

I made sure to grab the CoolProp.dll from SourceForge. In fact, I've tried several CoolProp.dll's from several places in the SourceForge under 6.0.0 in case I needed either 32 or 64bit. I can't get any of it to work.

I've also tried following the steps to get the C# wrapper example to compile, without success.

I had to go back to 4.0.0 to have any success with the C# wrapper. Any help would be appreciated. Thank you!

**Comment by ibell** [comment] 2016-08-19 15:29
Have  you tried the new .Net wrappers: http://www.coolprop.org/coolprop/wrappers/Csharp/index.html#csharp or http://www.coolprop.org/coolprop/wrappers/VB.net/index.html#vbdotnet ? They should be much easier to use and will give you access to the low-level interface natively.

**Comment by ibell** [comment] 2016-08-19 15:30
Also, if you want to compile the c# wrapper yourself, please try to follow our instructions to the letter and provide a complete build log.

**Comment by mattcasto** [comment] 2016-08-22 14:49
Following the directions at http://www.coolprop.org/coolprop/wrappers/Csharp/index.html#csharp I did the following...

1. Downloaded `Example.cs` from https://sourceforge.net/projects/coolprop/files/CoolProp/6.0.0/Csharp/
2. Downloaded `platform-independent.7z` and extract it to `platform-independent` folder in the same location
3. Downloaded `CoolProp.dll` from https://sourceforge.net/projects/coolprop/files/CoolProp/6.0.0/Csharp/Windows_64bit/ and put it in the same location as the files above.
4. Verified the folder structure matching the instructions.
5. Ran the `csc Example.cs platform-independent/*.cs -platform:x64` command.

This resulted in the following output from the c# compiler:

> Microsoft (R) Visual C# Compiler version 1.3.1.60616
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
> platform-independent\Example.cs(7,11): error CS0101: The namespace 'ConsoleApplication1' already contains a definition for 'Program'
> platform-independent\Example.cs(9,21): error CS0111: Type 'Program' already defines a member called 'Main' with the same parameter types

Since the build didn't work from my console, I tried loading things into a Visual Studio 2015 project.

1. Created a new Visual Studio solution and project file.
2. Include `Example.cs`, `CoolProp.dll`, and all files under the `platform-independent` folder in the project.
3. Mark CoolProp.dll to always copy to the output directory in the file's properties.
4. Set the console project's properties to have ConsoleApplication1.Program as the startup object.

When I build the solution, I get the same errors:

> 1>------ Build started: Project: CoolProp.CSharp.Example.Console, Configuration: Debug Any CPU ------
> 1>C:\Temp\CoolProp_Csharp\platform-independent\Example.cs(7,11,7,18): error CS0101: The namespace 'ConsoleApplication1' already contains a definition for 'Program'
> 1>C:\Temp\CoolProp_Csharp\platform-independent\Example.cs(9,21,9,25): error CS0111: Type 'Program' already defines a member called 'Main' with the same parameter types
> ========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

When I looked into what's going on with this build issue, I found that there was already an Example.cs file in the platform-independent folder. Comparing the two files shows that they're the same, so I deleted the one in the platform-independent folder. The solution then builds. The csc command to build from console also works now.

At this point, if I run Example.exe or debug the Visual Studio solution, I get a run time error. Here's the output from the console:

> **************** INFORMATION ***************
> This example was auto-generated by the language-agnostic dev/scripts/example_generator.py script written by Ian Bell
> CoolProp version: 6.0.0
> CoolProp gitrevision: df13df7756aa9352c56ef6f8d631365be590533c
> CoolProp Fluids: 1-Butene,Acetone,Air,Ammonia,Argon,Benzene,CarbonDioxide,CarbonMonoxide,CarbonylSulfide,cis-2-Butene,CycloHexane,Cyclopentane,CycloPropane,D4,D5,D6,Deuterium,Dichloroethane,DiethylEther,DimethylCarbonate,DimethylEther,Ethane,Ethanol,EthylBenzene,Ethylene,EthyleneOxide,Fluorine,HeavyWater,Helium,HFE143m,Hydrogen,HydrogenChloride,HydrogenSulfide,IsoButane,IsoButene,Isohexane,Isopentane,Krypton,m-Xylene,MD2M,MD3M,MD4M,MDM,Methane,Methanol,MethylLinoleate,MethylLinolenate,MethylOleate,MethylPalmitate,MethylStearate,MM,n-Butane,n-Decane,n-Dodecane,n-Heptane,n-Hexane,n-Nonane,n-Octane,n-Pentane,n-Propane,n-Undecane,Neon,Neopentane,Nitrogen,NitrousOxide,Novec649,o-Xylene,OrthoDeuterium,OrthoHydrogen,Oxygen,p-Xylene,ParaDeuterium,ParaHydrogen,Propylene,Propyne,R11,R113,R114,R115,R116,R12,R123,R1233zd(E),R1234yf,R1234ze(E),R1234ze(Z),R124,R125,R13,R134a,R13I1,R14,R141b,R142b,R143a,R152A,R161,R21,R218,R22,R227EA,R23,R236EA,R236FA,R245ca,R245fa,R32,R365MFC,R40,R404A,R407C,R41,R410A,R507A,RC318,SES36,SulfurDioxide,SulfurHexafluoride,Toluene,trans-2-Butene,Water,Xenon
> *********** HIGH LEVEL INTERFACE *****************
> Critical temperature of water: 647.096 K
> Boiling temperature of water at 101325 Pa: 373.124295847684 K
> Phase of water at 101325 Pa and 300 K: liquid
> c_p of water at 101325 Pa and 300 K: 4180.63577655606 J/kg/K
> c_p of water (using derivatives) at 101325 Pa and 300 K: 4180.63577655606 J/kg/K
> *********** HUMID AIR PROPERTIES *****************
> Humidity ratio of 50% rel. hum. air at 300 K, 101325 Pa: 0.0110955297054288 kg_w/kg_da
> Relative humidity from last calculation: 0.5 (fractional)
> *********** INCOMPRESSIBLE FLUID AND BRINES *****************
> Density of 50% (mass) ethylene glycol/water at 300 K, 101325 Pa: 1061.17930772046 kg/m^3
> Viscosity of Therminol D12 at 350 K, 101325 Pa: 0.000522883799095536 Pa-s
> *********** REFPROP *****************
> Good news: It is possible to use REFPROP on your system! However, the library
> could not be loaded. Please make sure that REFPROP is available on your system.
> 
> Neither found in current location nor found in system PATH.
> If you already obtained a copy of REFPROP from http://www.nist.gov/srd/,
> add location of REFPROP to the PATH environment variable or your library path.
> 
> In case you do not use Windows, have a look at https://github.com/jowr/librefprop.so
> to find instructions on how to compile your own version of the REFPROP library.
> 
> 
> Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
>    at CoolPropPINVOKE.get_global_param_string(String jarg1)
>    at CoolProp.get_global_param_string(String ParamName)
>    at ConsoleApplication1.Program.Main(String[] args)

**Comment by ibell** [comment] 2016-08-23 02:25
Aha, so the root of the problem is that we need to not package the
Example.cs file in the platform-independent folder.  I'll make that fix.

You don't have REFPROP installed on your computer, which is why the Example
script dies once you hit that line.  If you don't want to run the REFPROP
code, just comment it out.  Otherwise, all seems fine.

**Comment by mattcasto** [comment] 2016-08-23 18:03
It turns out the problem I had with the Visual Studio solution was that it needed to target x64 properly.

Thanks for your help!

**Comment by mattcasto** [comment] 2016-08-23 18:04
Oops, I didn't realize closing this issue removed it from the milestone. Re-opening.

**Comment by ibell** [comment] 2016-08-24 03:25
I believe this commit should have fixed it.  Let me know once the files are regenerated.

**Comment by ibell** [comment] 2016-08-25 04:22
If you have problems, feel free to reopen.  Closing for now...

**Closed by ibell** 2016-08-25 04:22 UTC
