### ISSUE TITLE
Multi-output library function

### ISSUE THREAD

**Issue by jowr** [CoolProp/CoolProp#888] opened 2015-12-03 08:54 UTC
Let us agree on a new function for the CoolProp interface as a follow up regarding the discussion on the mailing list. 
My new suggestion is:
```C++
// A function with the most common outputs, `value1` and `value2` are arrays of the length `length`
// and so are the output properties `T`, `p`, `rho`, `h`, `s`
EXPORT_CODE void CONVENTION AbstractState_update_common(const long handle, const long input_pair, const double* value1, const double* value2, const long length, double* T, double* p, double* rho, double* h, double* s)

// A function with selected outputs, `value1` and `value2` are arrays of the length `length`
// and so are the output pointers 
// `out0`, `out1`, `out2`, `out3`, `out4`, `out5`, `out6`, `out7`, `out8` and `out9`.
// The outputs are filled according to the content of the `outputs` array of the length
// `output_len` that contains long keys from `CoolProp::parameters`
EXPORT_CODE void CONVENTION AbstractState_update_output(const long handle, const long input_pair, const double* value1, const double* value2, const long length, double* out0, double* out1, double* out2, double* out3, double* out4, double* out5, double* out6, double* out7, double* out8, double* out9, const long* outputs, const long output_len)
```

**Comment by EdoMacchi** [comment] 2015-12-03 11:03
For me this should work. I did a test with a similar function (with pointers but not with arrays) and it works. The problem is that the performances of this new function (for update+computation of rho and Cp) are worse than the one of the standard functions (three different calls). Is it possible this is due to the use of pointers? Anyway probably the overall performances will improve when using arrays.

**Comment by EdoMacchi** [comment] 2015-12-03 11:25
Ok, tested with the arrays. This is much faster (probably even faster than the C++ low-level interface). I will post the C and Matlab code shortly.

**Comment by EdoMacchi** [comment] 2015-12-03 11:49
What I did is for two properties, but it can be easily generalized. Tested a bit the performances: in general slightly better than C++ low-level interface for HEOS (16 s vs 17 s) and TTSE (0.15 s vs 0.2 s) and better than C++ for BICUBIC (0.31 vs 0.75).

In CoolPropLib.cpp I added the function:

```C
EXPORT_CODE void CONVENTION AbstractState_updateCompProp(const long handle, const long input_pair, const double* value1, const double* value2, const long param1, const long param2, double* out1, double* out2, const long length)
{
        shared_ptr<CoolProp::AbstractState> &AS = handle_manager.get(handle);

        for (int i=0;i<length;i++){
        AS->update(static_cast<CoolProp::input_pairs>(input_pair), *(value1+i), *(value2+i));
        
        *(out1+i) = AS->keyed_output(static_cast<CoolProp::parameters>(param1));
        *(out2+i) = AS->keyed_output(static_cast<CoolProp::parameters>(param2));
        }

}
```

Then to use it in Matlab (starting from the last script posted in the mailing list):

```
Pptr = libpointer('doublePtr',P);
Tptr = libpointer('doublePtr',T);
out1ptr = libpointer('doublePtr',zeros(N,1));
out2ptr = libpointer('doublePtr',zeros(N,1));

calllib('cool','AbstractState_updateCompProp',handle,c_PT,Pptr,Tptr,c_rhomass,c_cpmass,out1ptr,out2ptr,N);
rho(:,1)=get(out1ptr,'Value');
Cp(:,1)=get(out2ptr,'Value');
```

Thank you for your suggestion!
Best regards,

Edo

**Comment by ibell** [comment] 2015-12-03 15:51
That is already looking good.

We obviously need to add error checking and things like that, but given the performance, seems well worth it.  

My proposal would be along the lines of @jowr :

``` c++
// A function with the most common outputs, `value1` and `value2` are arrays of the length `length`
// and so are the output properties `T`, `p`, `rho`, `h`, `s`
EXPORT_CODE void CONVENTION AbstractState_update_common(const long handle, const long input_pair, const double* value1, const double* value2, const long length, double* T, double* p, double* rhomolar, double* hmolar, double* smolar, char *errbuffer, long buffer_length)
```
Thinking about it, it could be useful to be able to pass an error message to say the handle is invalid, etc.
And then we have a generalized one, with up to 5 outputs:
``` c++
// A function with the most common outputs, `in1` and `in2` are arrays of the length `length`
// outputs is a 5-element array with the integer keys for the desired outputs.  Alternatively, it could be a delimited string, which would allow for returning derivatives.
EXPORT_CODE void CONVENTION AbstractState_update_common(const long handle, const long input_pair, const double* in1, const double* in2, const long length, const long *outputs, double* out1, double* out2, double* out3, double* out4, double* out5, char *errbuffer, long buffer_length)
```

**Comment by ibell** [comment] 2015-12-04 01:28
@EdoMacchi Are you willing to take this to the point of developing code that would be ready to be merged into CoolProp?  I don't think it would take too long.  It would be best if you could write the function, some docs, and open a pull request.

**Comment by EdoMacchi** [comment] 2015-12-04 12:08
I would like to help but since I don't know so much the code I think that it would take some time to get both functions working (this morning I tried with the simple one and I got some unexpected problems :( ). In addition right now I don't have a lot of free time... Maybe I can give you a hand with the documentation...

Update - found the problem: for some reason it didn't like the functions names (AbstractState_updateoutput_common, AbstractState_update_output_common and other two names that I tried).

Please find hereinafter the functions with the common outputs. Some more work is probably needed for the other function since it has to manage the case where there is no output for some pointers.

In CoolPropLib.h:

**Comment by ibell** [comment] 2015-12-14 01:38
Anyone have any recommendations for eliminating potential problems like not providing a large enough buffer?  For these, there isn't much we can do to protect ourselves against.  I vote we close this issue, and we can add others if there is a clear need.

**Closed** 2015-12-14 01:39 UTC
