### ISSUE TITLE
Error when using user compiled static library

### ISSUE THREAD

**Issue by uqtredd1** [CoolProp/CoolProp#1669] opened 2018-03-14 09:24 UTC
I am using Ubuntu 17.10 and have followed the instructions to build a static library using cmake from http://www.coolprop.org/coolprop/wrappers/StaticLibrary/index.html

The static library appeared to build without issues, however I am running into difficulties in the usage step. I have copied the code snippet main.cpp into the build directory of the form:

`~/repositories/CoolProp/build`

However, when attempting to compile with:

`g++ -ldl -L. -I./../include main.cpp -lCoolProp`

An error is returned:

In file included from ./../include/CoolPropTools.h:15:0,
                 from ./../include/DataStructures.h:11,
                 from ./../include/CoolProp.h:21,
                 from main.cpp:1:
./../include/CPstrings.h:13:14: fatal error: fmt/format.h: No such file or directory
     #include "fmt/format.h" // For addition of the string formatting functions and macros from cppformat

Also as a side note, the g++ command listed in the instructions appears to point to one directory too low, being given as -I../../include rather than -I./../include , unless I have misunderstood this step.

**Comment by ibell** [comment] 2018-03-15 03:14
Please see #1600

**Comment by uqtredd1** [comment] 2018-03-15 06:28
Hi Ian,

I've read through that issue however it does not seem to be identical. I tried adding the line:

`target_link_libraries (${LIB_NAME} ${CMAKE_DL_LIBS})`

to CMakeLists.txt, to no effect. It looks like its just not finding CoolProp/externals . Any ideas ?

**Comment by ibell** [comment] 2018-03-15 14:18
Sorry, I didn't read your issue closely enough. The issue is problably that you didn't do recursive clone initially, which you can fix with:

```
git submodule update --init
```

**Comment by ibell** [comment] 2018-03-16 03:09
Also, for this and other reasons, it is recommended to build your exe with CMake as well, because these horrible dependency issues will be seamlessly handled.

**Comment by uqtredd1** [comment] 2018-03-16 03:29
I used the recursive clone with:

`git clone https://github.com/CoolProp/CoolProp --recursive`

The externals folder is there, it just dosen't seem to automatically link to it for some reason. I tried modifying the g++ command to manually point to cppformat:

`g++ -ldl -L. -I../include main.cpp -I../externals/cppformat -lCoolProp`

Which fixed the previous error, but now leaves me with a bunch of undefined references:

./libCoolProp.a(REFPROPMixtureBackend.cpp.o): In function `getFunctionPointer(char const*, DLLNameManglingStyle)':
REFPROPMixtureBackend.cpp:(.text+0x268): undefined reference to `dlsym'
./libCoolProp.a(REFPROPMixtureBackend.cpp.o): In function `load_REFPROP(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
REFPROPMixtureBackend.cpp:(.text+0x10cd): undefined reference to `dlopen'
REFPROPMixtureBackend.cpp:(.text+0x10ff): undefined reference to `dlerror'
./libCoolProp.a(REFPROPMixtureBackend.cpp.o): In function `unload_REFPROP(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)':
REFPROPMixtureBackend.cpp:(.text+0x13d8): undefined reference to `dlclose'
REFPROPMixtureBackend.cpp:(.text+0x13ee): undefined reference to `dlerror'
./libCoolProp.a(REFPROPMixtureBackend.cpp.o): In function `CoolProp::REFPROPMixtureBackend::~REFPROPMixtureBackend()':
REFPROPMixtureBackend.cpp:(.text+0x2051): undefined reference to `dlclose'
collect2: error: ld returned 1 exit status

I might have a look at the cmake approach as well, although I have no experience with cmake. I mostly just wanted a static library so I could have a go at writing a wrapper for the D programming language.

**Comment by ibell** [comment] 2018-03-16 03:32
For that error, you need -ldl command line flag (also easily fixed with
cmake if you use cmake)

A D wrapper would be most welcome. SWIG supports D, so making a D wrapper
with SWIG (analogously to C#, Java etc.) would be the route I would
recommend, but I have no experience with D, and never made a D wrapper
before.

**Comment by uqtredd1** [comment] 2018-03-16 04:01
The -ldl command was already being used, it turns out it just had to be made the last argument:

`g++ -L. -I../include main.cpp -I../externals/cppformat -lCoolProp -ldl`

Compiles and works as expected. I'll let you know if I'm successful with the wrapper. D has partial support for direct c++ interop out of the box, so hopefully it will be reasonably straightforward.

Thanks for the help.

**Comment by ibell** [comment] 2018-03-17 16:54
Ok, since this issue is more or less resolved, I'm going to close it, and open a new one related to the D wrapper as an enhancement

**Closed by ibell** 2018-03-17 16:54 UTC
