### ISSUE TITLE
R1233zd(E) : discrepancy REFPROP/COOLPROP

### ISSUE THREAD

**Issue by tartieret** [CoolProp/CoolProp#1337] opened 2016-11-16 23:00 UTC
Hi,

While designing a new system, we found out a significant discrepancy with R1233zd(E) by comparing REFPROP and COOLPROP. As you can see on the following figure, an isentropic expansion process from (154°C, 26.8 bars) to (1.5 bar) results in a very different outlet temperature: 31.3°C with Coolprop, 47.95°C with REFPROP. 

![r1233zd](https://cloud.githubusercontent.com/assets/15146307/20369273/ed1d27be-ac0c-11e6-8fb6-c79f48d663ce.jpg)

Both software seems to rely on the same equation of state, so this difference is surprising. However REFPROP uses an pre-published version of the equation of state from 2013, while COOLPROP uses the one published in 2015. 

Any idea of what is happening here? Which code should we trust?

**Comment by ibell** [comment] 2016-11-17 01:11
What version of REFPROP do you use?  I suspect you are using 9.1.1, and the
preliminary EOS for R1233zd(E).  I'll double check, but in this case I
think CoolProp is one you should trust...

**Comment by tartieret** [comment] 2016-11-17 01:19
Yes, REFPROP 9.1 , the latest version. Yes, it is the preliminary EOS for R1233zd. Thanks for the feedback!
<img width="346" alt="refporp" src="https://cloud.githubusercontent.com/assets/15146307/20372531/c838d506-ac20-11e6-8d73-3b67c98b29e5.png">

**Comment by jowr** [comment] 2016-11-17 08:16
To me it looks like the problem is the entropy. I assume that both processes end on the same isobar, but the entropy calculated by REFPROP for point 1 (154°C, 26.8 bar) seems higher. If you need to quantify the difference even more, you might want to look at the partial derivatives of the entropy, eg ds/dT|p. We might want to close this for now since it is not really a bug in CoolProp.

**Closed by jowr** 2016-11-17 08:16 UTC
