### ISSUE TITLE
version 6.1.0 not available from pypi

### ISSUE THREAD

**Issue by rbozinoski** [CoolProp/CoolProp#1309] opened 2016-11-02 13:12 UTC
I'm not sure if you guys are aware of this but there doesn't seem to be any python wheels available from pypi for v6.1. When you try an install using pip you get version 6.0

**Comment by ibell** [comment] 2016-11-02 13:13
Interesting, I didn't know that.  I'm releasing 6.2 very soon because of a
rather serious bug, I'll deal with it then.

**Comment by ibell** [comment] 2016-11-13 03:41
Fixed.

**Comment by jowr** [comment] 2017-02-10 12:53
Is this really fixed? I still get v6.0.0 from `pip install coolprop` for Python 3.6 on Windows x64

**Comment by ibell** [comment] 2017-02-10 15:26
Yes, we didn't build wheels for 3.6 since that didn't exist at the time.
But with py <= 3.5, 6.0 should be available.

**Comment by ibell** [comment] 2017-02-10 15:26
Whoops, 6.1.0

**Comment by thorade** [comment] 2017-07-14 07:43
Just ran `pip install -U coolprop` in a fresh Anaconda with Python 3.6 and it tried to install 6.0.0, but that failed.

**Comment by ibell** [comment] 2017-07-18 20:52
As it should, we don't have 3.6 wheels for older versions

**Comment by thorade** [comment] 2017-10-04 09:38
There are no wheels for CoolProp 6.1 and Python 3.6, and no Source on PyPi:
https://pypi.python.org/pypi/CoolProp/6.1.0
and there are no wheels for 6.0 and 3.6, but there is a source distribution:
https://pypi.python.org/pypi/CoolProp/6.0.0

So, when running `pip install coolprop` from py36, it will download the coolprop 6.0 source distribution and try to build it.

This should be fixed by either 
- adding a 6.1 wheel for py36
- adding a 6.1 source distribution
- releasing 6.2 including a 3.6 wheel and a source distribution

**Comment by thorade** [comment] 2017-11-29 09:24
Closing as duplicate of #1604.
Just make sure to always add a source release as fallback when releasing to PyPI,
in addition to the wheels.

**Closed by thorade** 2017-11-29 09:24 UTC
