### ISSUE TITLE
REFPROP v10.0 enthalpy/pressure look-up bug

### ISSUE THREAD

**Issue by milesabarr** [CoolProp/CoolProp#1724] opened 2018-08-09 15:18 UTC
### Description
I upgraded to version 10 of REFPROP, but I am now running into issues with some enthalpy and pressure look-ups (which are not an issue in REFPROP version 9.1).

### Steps to Reproduce
The following code:
```
import CoolProp
state = CoolProp.AbstractState("REFPROP", "Water")
state.update(CoolProp.HmassP_INPUTS, 536e3, 60e5)
```
Gives this error:
```
Traceback (most recent call last):
  File "..\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-14-06bff1a0fa47>", line 3, in <module>
    state.update(CoolProp.HmassP_INPUTS, 536e3, 60e5)
  File "CoolProp/AbstractState.pyx", line 81, in CoolProp.CoolProp.AbstractState.update (CoolProp\CoolProp.cpp:16429)
  File "CoolProp/AbstractState.pyx", line 83, in CoolProp.CoolProp.AbstractState.update (CoolProp\CoolProp.cpp:16318)
ValueError: HmolarPmolar: [PHFLSH error 16] One or more inputs are out of range; Inputs are within the solid phase.                                                                                                                                                                     
```
I also get this error when using the High Level Interface, i.e.:
```
import CoolProp.CoolProp as CP
CP.PropsSI("T", "H", 536e3, "P", 60e5, "REFPROP::Water")
```

### Versions
- Python version 3.6.5
- CoolProp version 6.0.0
- REFPROP version 10
- Windows 10
- Using the Python Console in PyCharm Community 2018.1

**Comment by ibell** [comment] 2018-08-09 15:45
Interesting, the reference state for water should not have changed, wonder
what is going on here.

**Comment by ibell** [comment] 2018-08-10 03:06
And with 9.1 you don't see this error, right?

**Comment by milesabarr** [comment] 2018-08-10 14:52
Correct, I can swap out my REFPROP folder back to 9.1, and all my code runs smoothly.

**Comment by ianhbell** [comment] 2018-08-19 01:15
Confirmed.

Comment out set or the other; the first one works fine, the second yields error below.

``` python
import CoolProp, CoolProp.CoolProp as CP
# CP.set_config_string(CP.ALTERNATIVE_REFPROP_PATH, r'c:/Program Files (x86)/REFPROP') # 9.1.1
# state = CoolProp.AbstractState("REFPROP", "Water")
# state.update(CoolProp.HmassP_INPUTS, 536e3, 60e5)
CP.set_config_string(CP.ALTERNATIVE_REFPROP_PATH, r'D:/REFPROP') # 10.0
state = CoolProp.AbstractState("REFPROP", "Water")
state.update(CoolProp.HmassP_INPUTS, 536e3, 60e5)
```
yields
```
Traceback (most recent call last):
  File "C:\Users\ihb\Desktop\REFPROP_water.py", line 8, in <module>
    state.update(CoolProp.HmassP_INPUTS, 536e3, 60e5)
  File "CoolProp\AbstractState.pyx", line 102, in CoolProp.CoolProp.AbstractState.update (CoolProp\CoolProp.cpp:22356)
  File "CoolProp\AbstractState.pyx", line 104, in CoolProp.CoolProp.AbstractState.update (CoolProp\CoolProp.cpp:22248)
ValueError: HmolarPmolar: [PHFLSH error 16] One or more inputs are out of range; Inputs are within the solid phase.                                                                                                                                                                     
[Finished in 0.4s with exit code 1]
```

**Comment by EricLemmon** [comment] 2018-08-20 19:41
Refprop 10.0 found a solution at a temperature far below that valid for water, but which met all criteria as a valid state point (due to the behavior of the equation of state outside its region of validity).  Please contact us directly at Eric.Lemmon@nist.gov for an updated DLL.

**Comment by ianhbell** [comment] 2018-12-04 15:44
Yeah, we can close this issue, fixed in REFPROP.

**Closed by ianhbell** 2018-12-04 15:44 UTC
Labels: bug
