### ISSUE TITLE
pip install CoolProp fails on Arch Linux

### ISSUE THREAD

**Issue by kylgry** [CoolProp/CoolProp#1558] opened 2017-10-02 15:43 UTC
Here is the output https://pastebin.com/s0SdXcz4

I am using python 3.6.2 and gcc 7.2.0. 

Also, pip installs CoolProp 6.0.0, even though the latest version on PyPI appears to be 6.1.0. 

I tried installing the latest nightly release using the method from below, but get a different set of errors. 

http://www.coolprop.org/coolprop/wrappers/Python/index.html

**Comment by thorade** [comment] 2017-10-04 09:23
Seems to be a duplicate of https://github.com/CoolProp/CoolProp/issues/1309#issuecomment-315294334
The easiest fix for now is to install the nightlies as described here:
http://www.coolprop.org/dev/coolprop/wrappers/Python/index.html

What does `python -m pip --version` show you?
https://docs.python.org/3/installing/
https://docs.python.org/3/installing/#work-with-multiple-versions-of-python-installed-in-parallel

**Closed by thorade** 2017-10-04 09:23 UTC

**Comment by kylgry** [comment] 2017-10-04 14:40
I just tried installing the nightlies again and this time they worked. Thanks.

python --version is 3.6.2
pip --version is 9.0.1
python -m pip --version is 9.0.1

**Comment by ibell** [comment] 2017-10-05 02:40
Alternatively, building from source is also pretty painless and works more
reliably because you are linking against the standard libraries that are
actually on your computer.  Glad to hear the nightlies worked though.
