### ISSUE TITLE
Coolprop.Coolprop module does not exist

### ISSUE THREAD

**Issue by Takmaster1987** [CoolProp/CoolProp#1682] opened 2018-03-27 22:02 UTC
Hi,
I'm fairly new to Python and tried installing the Coolprop python wrapper.

Downloaded from : pip install -vvv --pre --trusted-host www.coolprop.dreamhosters.com --find-links http://www.coolprop.dreamhosters.com/binaries/Python/ -U --force-reinstall CoolProp

No errors installing

However, when I try some Coolprop code in Anaconda, I get the following error 
"No module named CoolProp.Coolprop"

![capture](https://user-images.githubusercontent.com/32304168/37997461-ed999f3e-31e8-11e8-8b61-2f63859cc6f5.JPG)

I am using Python3.6.4 

Furthermore , if I look at the CoolProp directory, I don't have the expected CoolProp attributes (PropsSI, etc)

![coolprop directory](https://user-images.githubusercontent.com/32304168/37997628-7a766a22-31e9-11e8-85ea-4d620e100b20.JPG)

What could be the problem?

**Comment by ibell** [comment] 2018-03-27 23:47
Hi.  Welcome to python and coolprop!  Do you have multiple conda
environments installed?  That is often the cause of issues like this.  The
jupyter notebook is not synced by default with the current environment.  So
that's the first thing I would check.

**Comment by Takmaster1987** [comment] 2018-03-28 03:45
Thanks very much for the quick reply!

I only had one conda environment installed.

Looking at Coolprop's site,  I see that their latest wheel file is for Python 3.5  (I had Python 3.6)

https://pypi.python.org/pypi/CoolProp

Oddly enough, the Coolprop .py file is available for Python 3.6

This is why I was able to install the Python module but none of the attributes from the wheel file.

I installed Python 2.7 and the corresponding wheel file  and it works now!!

**Comment by ibell** [comment] 2018-03-28 05:28
The first call to install from the development server should work for
python 3.6 because we are now providing binary wheels for python 3.6, (but
6.2 hasn't been released yet, which will be on PYPI).  Can you please
provide the log for your install from pip?  That would be very instructive
to debug what is going on.  Python 2.7 is nearing end-of-life.

**Comment by thorade** [comment] 2018-04-16 08:32
Few more ideas:
You can just run the pip install command you posted again.
http://www.coolprop.org/coolprop/wrappers/Python/index.html
Then afterwards, run `pip show --verbose coolprop`.

Generally, it is recommended to use `python -m pip ...` to make sure the corresponding python and pip are used.

Then, it is also possible to call pip from a Jupyter notebook, with a snippet like this:
```python
# Install a pip package in the current Jupyter kernel
import sys
!{sys.executable} -m pip install -U numpy
```
Taken from https://jakevdp.github.io/blog/2017/12/05/installing-python-packages-from-jupyter/

**Comment by thorade** [comment] 2018-04-18 13:44
@Takmaster1987 I'll close this, as you said it works for you with py27 now.
It should also work with py36, and it will work for sure once coolprop 6.2 has been released.

**Closed by thorade** 2018-04-18 13:44 UTC
