### ISSUE TITLE
pentane properties coolprop vs NIST chemistry webbook

### ISSUE THREAD

**Issue by krule012** [CoolProp/CoolProp#1541] opened 2017-08-28 15:05 UTC
viscosity using Coolprop 6.1.1.dev0: @150K and 1 atm --> viscosity = 522 Pa-s
viscosity using NIST Webbook, SRD69: @150K and 1 atm --> viscosity= 2754 Pa-s

I had asked about this difference before (on the deprecated repository for coolprop v4) and I'm still troubled by the difference between these two databases. NIST Webbook uses Refprop v7. This difference has a dramatic effect when modeling using this fluid. Could you confirm that the coolprop value is more accurate?

It looks like coolprop uses the following source for calculating viscosity: Sergio E. Quiñones-Cisneros and Ulrich K. Deiters. Generalization of the Friction Theory for Viscosity Modeling. J. Phys. Chem. B, 110:12820–12834, 2006. doi:10.1021/jp0618577.

This seems newer than any of the references that I can find for pentane in the NIST Webbook/Refprop v7, but I don't have access to Refprop v7 directly, so I can't confirm.

**Comment by jowr** [comment] 2017-08-28 17:24
As you can see here (http://coolprop.sourceforge.net/dev/fluid_properties/fluids/n-Pentane.html#refprop-validation-data) CoolProp vs REFPROP v9.1.1.10 yields as difference of up to 100 per cent for transport properties along the critical isotherm. The difference you at state is around 85 per cent as calculated by (V_CP/V_RP-1)*100%, which does not surprise me. I guess you have to dig into the literature to find out which value you would like to use.

**Comment by ibell** [comment] 2017-08-30 04:22
There are a couple of models out there for viscosity of pentane.  The model
implemented in REFPROP is unpublished, and as a result, not available for
use in CoolProp, which tries to only use published models.  On some
occasions I have asked for permission to use models from REFPROP; before
that was ok, but not anymore.

**Comment by jowr** [comment] 2017-08-30 11:26
I consider this closed since this is not a bug, but mere a lack of published data. @krule012, please close this issue if you agree.

**Comment by thorade** [comment] 2017-12-13 12:16
Closing for now, but @krule012 can re-open it any time.
http://coolprop.sourceforge.net/dev/fluid_properties/fluids/n-Pentane.html

**Closed by thorade** 2017-12-13 12:16 UTC
