### ISSUE TITLE
catch.hpp file was not found

### ISSUE THREAD

**Issue by gusbonolo** [CoolProp/CoolProp#1807] opened 2019-03-13 12:33 UTC

**Comment by ibell** [comment] 2019-03-13 22:05
I think you might want to undo your edits...

Nonetheless, I can be quite confident that I know what the problem is.  You need to recursively clone the repository to ensure that all the dependencies are pulled in correctly.  I assume you downloaded a zip file from github?

Please see an example of the correct approach here: http://www.coolprop.org/coolprop/wrappers/SharedLibrary/index.html#user-compiled-binaries  You'll need to meet the requirements listed there.

**Comment by jowr** [comment] 2019-04-04 18:43
I guess that it was the recursive clone issue - I'll close this issue for now. Please reopen if necessary.

**Closed by jowr** 2019-04-04 18:43 UTC
