### ISSUE TITLE
Can't compute properties of SES36 for (H,S) inputs or (H,D) inputs

### ISSUE THREAD

**Issue by Astrinus** [CoolProp/CoolProp#616] opened 2015-04-23 09:42 UTC
I'm working on SES36 and I have some problems when I use enthalpy as an input along with entropy or density, although in the latter case it happens in a smaller region, only on a subset of the twophase region.
It seems that for S < 1613 J/kg/K or D < 784 kg/m^3 the routine fails...

```
>> CoolProp.PropsSI('S','P',4.6e5,'Q',0,'SES36')
    ans = 1337.2
>> CoolProp.PropsSI('H','P',4.6e5,'Q',0,'SES36')
    ans = 2.9082e+05
>> CoolProp.PropsSI('S','P',4.6e5,'Q',1,'SES36')
    ans = 1700.1
>> CoolProp.PropsSI('H','P',4.6e5,'Q',1,'SES36')
    ans = 4.2295e+05
>> CoolProp.PropsSI('P','S',1337,'H',2.91e5,'SES36')
    Warning: Unable to invert ancillary equation for sL for value -102.45 with Tminval -203.428 and Tmaxval -1.#IND
>> CoolProp.PropsSI('P','S',1600,'Hmass',3.5e5,'SES36')
    Warning: Unable to invert ancillary equation for sL for value -53.8349 with Tminval -203.428 and Tmaxval -1.#IND
>> CoolProp.PropsSI('P','S',1400,'Hmass',3.5e5,'SES36')
    Warning: Unable to invert ancillary equation for sL for value -90.8049 with Tminval -203.428 and Tmaxval -1.#IND  
>> CoolProp.PropsSI('P','S',1613,'Hmass',4.2e5,'SES36')
    ans = 2.0621e+07
>> CoolProp.PropsSI('P','S',1612,'Hmass',4.21e5,'SES36')
    Warning: Unable to invert ancillary equation for sL for value -51.6167 with Tminval -203.428 and Tmaxval -1.#IND  
>> CoolProp.PropsSI('D','P',4.6e5,'Q',0.5,'SES36')
    ans = 64.795
>> CoolProp.PropsSI('H','P',4.6e5,'Q',0.5,'SES36')
    ans = 3.5689e+05
>> CoolProp.PropsSI('P','D',64.795,'H',3.57e5,'SES36')
    Warning: p is not a valid number 
>> CoolProp.PropsSI('T','H',4.23e5,'D',784,'SES36')
    ans = 441.44
>> CoolProp.PropsSI('T','H',4.23e5,'D',783,'SES36');
    Warning: p is not a valid number 
```

**Comment by jowr** [comment] 2015-04-23 11:39
h,s is a very tough combination for the solver. Try to get around it, if you can. Since h,p works reliably, I would assume that h,d works as well, but I haven't looked at the new solvers recently. I am afraid you have to wait for @ibell to help you out. If you are using the development version, try turning on TTSE, that sometimes helps in situations where the solver gets stuck.

**Comment by Astrinus** [comment] 2015-04-23 14:47
No, I'm using 5.0.8. How would you get around that issue if you need an isenthalpic transformation?

**Comment by ibell** [comment] 2015-04-24 03:50
See also http://www.coolprop.org/dev/fluid_properties/fluids/SES36.html#consistency-plots

**Comment by ibell** [comment] 2015-04-24 03:51
If you have a good guess value for the state (python, right?) you could write your own little solver based on scipy.optimize.newton(http://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.optimize.newton.html)

**Comment by Astrinus** [comment] 2015-04-24 06:55
No, Matlab (output has been squeezed) and Simulink.
Yes, I could use fzero or something like that, but density example was a (failed) attempt to get around in a offline way, but I need an online solution for simulation. Most part of the simulation takes 5 hours (200k simulated seconds: yes, we have a ratio of 11 simulated seconds per second!) to complete without the actuated valve: it is not feasible to solve iteratively at every step, and this will further shorten the step size chosen by Simulink (the system is highly stiff and not well numerically condtitioned).

**Comment by ibell** [comment] 2015-04-24 15:13
H,S are really, really nasty inputs and introduce a wide range of problems
in the numerical solver.  Can you provide a good guess value for the
density and the temperature when you provide H,S?  If so, I could further
extend the update_with_guesses function in AbstractState to allow you to
provide guesses for T, D.

Have you looked at tabular interpolation:
http://www.coolprop.org/dev/coolprop/Tabular.html  It's available from
MATLAB.

**Comment by Astrinus** [comment] 2015-04-27 07:47
It is a bit difficult since some blocks must be rewrote to handle density (which is currently ignored, handling only T, P, S and H, but there are convergence problem if I use T and P for isenthalpic transformations). Anyway, that section of the project has been delayed, so don't put too much effort in this issue. In the future, we'll rewrite some of the blocks. Thanks anyway.

**Comment by ibell** [comment] 2015-04-27 15:55
I made significant improvements to HS inputs, but they are much slower now.
SES36 isn't a great EOS, and that might be the cause of some of the
problems you see.  But I will see what I can do.  What is the most
important part of the property space for you?  Vapor? Liquid? Two-phase?

**Comment by Astrinus** [comment] 2015-04-28 10:14
Unfortunately, all, since I have to manage startup and shutdowns... However today I was told that it has been decided to switch to another fluid (for physical reasons)... not a very good news...

**Comment by ibell** [comment] 2015-04-28 13:59
Good news in terms of fluid properties though, is is a pure fluid you are
switching to?

**Comment by Astrinus** [comment] 2015-04-30 06:50
It should be. But we have to redo all the work.

**Comment by ibell** [comment] 2015-11-17 04:29
Are you still interested in this bug?  If so, can you check where we stand on this?

**Comment by Astrinus** [comment] 2015-11-17 07:51
Unfortunately we switched to R245fa. If you tell me what to test, I could do some in my spare time.

**Comment by thorade** [comment] 2017-02-03 10:00
Closing for now, as this issue was in CoolProp 5.0.8. and more than one year has passed since last comment.
If the problem persists in the latest release, please reopen.

**Closed by thorade** 2017-02-03 10:00 UTC
