### ISSUE TITLE
Failure to calculate any state using input pair QT_INPUTS with backend TTSE&REFPROP

### ISSUE THREAD

**Issue by mapipolo** [CoolProp/CoolProp#840] opened 2015-10-14 20:01 UTC
The following code produces bad state properties for any refrigerant, any value of Q, and any value of T (or so it appears—I've tried many permutations):

    AbstractState state = AbstractState.factory("TTSE&REFPROP", "R401a.mix");
    state.update(input_pairs.QT_INPUTS, 1.0, 290);
    double p = state.p();
    double h = state.hmass();
    double density = state.rhomass();

p becomes a near-zero or near-infinity number, and h, u, s, etc. become NaN. The rhomass() call throws an ApplicationException with the message "rhoV is invalid".

I understand CoolProp has limited functionality inside the vapor dome (i.e., no Cp or Cv); I'm interested in this input pair only for X=0 and X=1, and results are good when using either the non-tabular or the HEOS backends. This issue seems to be limited to the tabular REFPROP backend.

Using the nightly builds of CoolProp.dll and platform independent code with C# and REFPROP 9.12.

**Comment by ibell** [comment] 2015-10-15 06:01
Duplicate of #831? I think we don't have interaction parameters and it
fails in an unclear way but I need to investigate.

**Comment by mapipolo** [comment] 2015-10-15 12:28
It doesn't seem to be a duplicate, but perhaps they are related at some level. #831 is specifically an exception thrown by the bicubic method when working with any predefined mixture, and it occurs for all input pairs, not just QT. This one applies to TTSE* and does not result in a thrown exception upon calling state.update, but does always result in bad state properties.

* It likely applies to bicubic as well, but I can't get far enough to find out—updated title to reflect this.

**Closed** 2015-10-17 16:58 UTC
